DEFAULT_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'

DEFAULT_CLIENT_SERVICE_URLS = (
    'translate.googleapis.com',
)

DEFAULT_FALLBACK_SERVICE_URLS = (
    'translate.googleapis.com',
)

DEFAULT_SERVICE_URLS = ('translate.google.ac', 'translate.google.ad', 'translate.google.ae',
                        'translate.google.al', 'translate.google.am', 'translate.google.as',
                        'translate.google.at', 'translate.google.az', 'translate.google.ba',
                        'translate.google.be', 'translate.google.bf', 'translate.google.bg',
                        'translate.google.bi', 'translate.google.bj', 'translate.google.bs',
                        'translate.google.bt', 'translate.google.by', 'translate.google.ca',
                        'translate.google.cat', 'translate.google.cc', 'translate.google.cd',
                        'translate.google.cf', 'translate.google.cg', 'translate.google.ch',
                        'translate.google.ci', 'translate.google.cl', 'translate.google.cm',
                        'translate.google.cn', 'translate.google.co.ao', 'translate.google.co.bw',
                        'translate.google.co.ck', 'translate.google.co.cr', 'translate.google.co.id',
                        'translate.google.co.il', 'translate.google.co.in', 'translate.google.co.jp',
                        'translate.google.co.ke', 'translate.google.co.kr', 'translate.google.co.ls',
                        'translate.google.co.ma', 'translate.google.co.mz', 'translate.google.co.nz',
                        'translate.google.co.th', 'translate.google.co.tz', 'translate.google.co.ug',
                        'translate.google.co.uk', 'translate.google.co.uz', 'translate.google.co.ve',
                        'translate.google.co.vi', 'translate.google.co.za', 'translate.google.co.zm',
                        'translate.google.co.zw', 'translate.google.com.af', 'translate.google.com.ag',
                        'translate.google.com.ai', 'translate.google.com.ar', 'translate.google.com.au',
                        'translate.google.com.bd', 'translate.google.com.bh', 'translate.google.com.bn',
                        'translate.google.com.bo', 'translate.google.com.br', 'translate.google.com.bz',
                        'translate.google.com.co', 'translate.google.com.cu', 'translate.google.com.cy',
                        'translate.google.com.do', 'translate.google.com.ec', 'translate.google.com.eg',
                        'translate.google.com.et', 'translate.google.com.fj', 'translate.google.com.gh',
                        'translate.google.com.gi', 'translate.google.com.gt', 'translate.google.com.hk',
                        'translate.google.com.jm', 'translate.google.com.kh', 'translate.google.com.kw',
                        'translate.google.com.lb', 'translate.google.com.ly', 'translate.google.com.mm',
                        'translate.google.com.mt', 'translate.google.com.mx', 'translate.google.com.my',
                        'translate.google.com.na', 'translate.google.com.ng', 'translate.google.com.ni',
                        'translate.google.com.np', 'translate.google.com.om', 'translate.google.com.pa',
                        'translate.google.com.pe', 'translate.google.com.pg', 'translate.google.com.ph',
                        'translate.google.com.pk', 'translate.google.com.pr', 'translate.google.com.py',
                        'translate.google.com.qa', 'translate.google.com.sa', 'translate.google.com.sb',
                        'translate.google.com.sg', 'translate.google.com.sl', 'translate.google.com.sv',
                        'translate.google.com.tj', 'translate.google.com.tr', 'translate.google.com.tw',
                        'translate.google.com.ua', 'translate.google.com.uy', 'translate.google.com.vc',
                        'translate.google.com.vn', 'translate.google.com', 'translate.google.cv',
                        'translate.google.cz', 'translate.google.de', 'translate.google.dj',
                        'translate.google.dk', 'translate.google.dm', 'translate.google.dz',
                        'translate.google.ee', 'translate.google.es', 'translate.google.eu',
                        'translate.google.fi', 'translate.google.fm', 'translate.google.fr',
                        'translate.google.ga', 'translate.google.ge', 'translate.google.gf',
                        'translate.google.gg', 'translate.google.gl', 'translate.google.gm',
                        'translate.google.gp', 'translate.google.gr', 'translate.google.gy',
                        'translate.google.hn', 'translate.google.hr', 'translate.google.ht',
                        'translate.google.hu', 'translate.google.ie', 'translate.google.im',
                        'translate.google.io', 'translate.google.iq', 'translate.google.is',
                        'translate.google.it', 'translate.google.je', 'translate.google.jo',
                        'translate.google.kg', 'translate.google.ki', 'translate.google.kz',
                        'translate.google.la', 'translate.google.li', 'translate.google.lk',
                        'translate.google.lt', 'translate.google.lu', 'translate.google.lv',
                        'translate.google.md', 'translate.google.me', 'translate.google.mg',
                        'translate.google.mk', 'translate.google.ml', 'translate.google.mn',
                        'translate.google.ms', 'translate.google.mu', 'translate.google.mv',
                        'translate.google.mw', 'translate.google.ne', 'translate.google.nf',
                        'translate.google.nl', 'translate.google.no', 'translate.google.nr',
                        'translate.google.nu', 'translate.google.pl', 'translate.google.pn',
                        'translate.google.ps', 'translate.google.pt', 'translate.google.ro',
                        'translate.google.rs', 'translate.google.ru', 'translate.google.rw',
                        'translate.google.sc', 'translate.google.se', 'translate.google.sh',
                        'translate.google.si', 'translate.google.sk', 'translate.google.sm',
                        'translate.google.sn', 'translate.google.so', 'translate.google.sr',
                        'translate.google.st', 'translate.google.td', 'translate.google.tg',
                        'translate.google.tk', 'translate.google.tl', 'translate.google.tm',
                        'translate.google.tn', 'translate.google.to', 'translate.google.tt',
                        'translate.google.us', 'translate.google.vg', 'translate.google.vu',
                        'translate.google.ws')

SPECIAL_CASES = {
    'ee': 'et',
}

LANGUAGES = {
    'ab' : 'abkhaz',
    'ace' : 'acehnese',
    'ach' : 'acholi',
    'aa' : 'afar',
    'af' : 'afrikaans',
    'sq' : 'albanian',
    'alz' : 'alur',
    'am' : 'amharic',
    'ar' : 'arabic',
    'hy' : 'armenian',
    'as' : 'assamese',
    'av' : 'avar',
    'awa' : 'awadhi',
    'ay' : 'aymara',
    'az' : 'azerbaijani',
    'ban' : 'balinese',
    'bal' : 'baluchi',
    'bm' : 'bambara',
    'bci' : 'baoulé',
    'ba' : 'bashkir',
    'eu' : 'basque',
    'btx' : 'batak karo',
    'bts' : 'batak simalungun',
    'bbc' : 'batak toba',
    'be' : 'belarusian',
    'bem' : 'bemba',
    'bn' : 'bengali',
    'bew' : 'betawi',
    'bho' : 'bhojpuri',
    'bik' : 'bikol',
    'bs' : 'bosnian',
    'br' : 'breton',
    'bg' : 'bulgarian',
    'bua' : 'buryat',
    'yue' : 'cantonese',
    'ca' : 'catalan',
    'ceb' : 'cebuano',
    'ch' : 'chamorro',
    'ce' : 'chechen',
    'ny' : 'chichewa',
    'zh-CN' : 'chinese (simplified)',
    'zh-TW' : 'chinese (traditional)',
    'chk' : 'chuukese',
    'cv' : 'chuvash',
    'co' : 'corsican',
    'crh' : 'crimean tatar',
    'crh-Latn': 'crimean tatar (latin)',
    'hr' : 'croatian',
    'cs' : 'czech',
    'da' : 'danish',
    'fa-AF' : 'dari',
    'dv' : 'dhivehi',
    'din' : 'dinka',
    'doi' : 'dogri',
    'dov' : 'dombe',
    'nl' : 'dutch',
    'dyu' : 'dyula',
    'dz' : 'dzongkha',
    'en' : 'english',
    'eo' : 'esperanto',
    'et' : 'estonian',
    'ee' : 'ewe',
    'fo' : 'faroese',
    'fj' : 'fijian',
    'tl' : 'filipino',
    'fi' : 'finnish',
    'fon' : 'fon',
    'fr' : 'french',
    #'fr-CA': 'french (canada)',
    'fy' : 'frisian',
    'fur' : 'friulian',
    'ff' : 'fulani',
    'gaa' : 'ga',
    'gl' : 'galician',
    'ka' : 'georgian',
    'de' : 'german',
    'el' : 'greek',
    'gn' : 'guarani',
    'gu' : 'gujarati',
    'ht' : 'haitian creole',
    'cnh' : 'hakha chin',
    'ha' : 'hausa',
    'haw' : 'hawaiian',
    'iw' : 'hebrew',
    'hil' : 'hiligaynon',
    'hi' : 'hindi',
    'hmn' : 'hmong',
    'hu' : 'hungarian',
    'hrx' : 'hunsrik',
    'iba' : 'iban',
    'is' : 'icelandic',
    'ig' : 'igbo',
    'ilo' : 'ilocano',
    'id' : 'indonesian',
    'iu' : 'inuktitut',
    'iu-Latn' : 'inuktitut (latin)',
    'ga' : 'irish',
    'it' : 'italian',
    'jam' : 'jamaican patois',
    'ja' : 'japanese',
    'jw' : 'javanese',
    'kac' : 'jingpo',
    'kl' : 'kalaallisut',
    'kn' : 'kannada',
    'kr' : 'kanuri',
    'pam' : 'kapampangan',
    'kk' : 'kazakh',
    'kha' : 'khasi',
    'km' : 'khmer',
    'cgg' : 'kiga',
    'kg' : 'kikongo',
    'rw' : 'kinyarwanda',
    'ktu' : 'kituba',
    'trp' : 'kokborok',
    'kv' : 'komi',
    'gom' : 'konkani',
    'ko' : 'korean',
    'kri' : 'krio',
    'ku' : 'kurdish (kurmanji)',
    'ckb' : 'kurdish (sorani)',
    'ky' : 'kyrgyz',
    'lo' : 'lao',
    'ltg' : 'latgalian',
    'la' : 'latin',
    'lv' : 'latvian',
    'lij' : 'ligurian',
    'li' : 'limburgish',
    'ln' : 'lingala',
    'lt' : 'lithuanian',
    'lmo' : 'lombard',
    'lg' : 'luganda',
    'luo' : 'luo',
    'lb' : 'luxembourgish',
    'mk' : 'macedonian',
    'mad' : 'madurese',
    'mai' : 'maithili',
    'mak' : 'makassar',
    'mg' : 'malagasy',
    'ms' : 'malay',
    'ms-Arab' : 'malay (jawi)',
    'ml' : 'malayalam',
    'mt' : 'maltese',
    'mam' : 'mam',
    'gv' : 'manx',
    'mi' : 'maori',
    'mr' : 'marathi',
    'mh' : 'marshallese',
    'mwr' : 'marwadi',
    'mfe' : 'mauritian creole',
    'chm' : 'meadow mari',
    'mni-Mtei' : 'meiteilon (manipuri)',
    'min' : 'minang',
    'lus' : 'mizo',
    'mn' : 'mongolian',
    'my' : 'myanmar (burmese)',
    'nhe' : 'nahuatl (eastern huasteca)',
    'ndc-ZW' : 'ndau',
    'nr' : 'ndebele (south)',
    'new' : 'nepalbhasa (newari)',
    'ne' : 'nepali',
    'bm-Nkoo' : 'nko',
    'no' : 'norwegian',
    'nus' : 'nuer',
    'oc' : 'occitan',
    'or' : 'odia',
    'om' : 'oromo',
    'os' : 'ossetian',
    'pag' : 'pangasinan',
    'pap' : 'papiamento',
    'ps' : 'pashto',
    'fa' : 'persian',
    'pl' : 'polish',
    'pt-PT' : 'portuguese',
    'pt' : 'portuguese (brazil)',
    'pa' : 'punjabi',
    'pa-Arab' : 'punjabi (shahmukhi)',
    'qu' : 'quechua',
    'kek' : 'qeqchi',
    'rom' : 'romani',
    'ro' : 'romanian',
    'rn' : 'rundi',
    'ru' : 'russian',
    'se' : 'sami (north)',
    'sm' : 'samoan',
    'sg' : 'sango',
    'sa' : 'sanskrit',
    'sat-Latn' : 'santali',
    'sat': 'santali (ol chiki)',
    'gd' : 'scots gaelic',
    'nso' : 'sepedi',
    'sr' : 'serbian',
    'st' : 'sesotho',
    'crs' : 'seychellois creole',
    'shn' : 'shan',
    'sn' : 'shona',
    'scn' : 'sicilian',
    'szl' : 'silesian',
    'sd' : 'sindhi',
    'si' : 'sinhala',
    'sk' : 'slovak',
    'sl' : 'slovenian',
    'so' : 'somali',
    'es' : 'spanish',
    'su' : 'sundanese',
    'sus' : 'susu',
    'sw' : 'swahili',
    'ss' : 'swati',
    'sv' : 'swedish',
    'ty' : 'tahitian',
    'tg' : 'tajik',
    'ber-Latn' : 'tamazight',
    'ber' : 'tamazight (tifinagh)',
    'ta' : 'tamil',
    'tt' : 'tatar',
    'te' : 'telugu',
    'tet' : 'tetum',
    'th' : 'thai',
    'bo' : 'tibetan',
    'ti' : 'tigrinya',
    'tiv' : 'tiv',
    'tpi' : 'tok pisin',
    'to' : 'tongan',
    'lua' : 'tshiluba',
    'ts' : 'tsonga',
    'tn' : 'tswana',
    'tcy' : 'tulu',
    'tum' : 'tumbuka',
    'tr' : 'turkish',
    'tk' : 'turkmen',
    'tyv' : 'tuvan',
    'ak' : 'twi',
    'udm' : 'udmurt',
    'uk' : 'ukrainian',
    'ur' : 'urdu',
    'ug' : 'uyghur',
    'uz' : 'uzbek',
    've' : 'venda',
    'vec' : 'venetian',
    'vi' : 'vietnamese',
    'war' : 'waray',
    'cy' : 'welsh',
    'wo' : 'wolof',
    'xh' : 'xhosa',
    'sah' : 'yakut',
    'yi' : 'yiddish',
    'yo' : 'yoruba',
    'yua' : 'yucatec maya',
    'zap' : 'zapotec',
    'zu' : 'zulu'
}

FLAG_CODES = {
    '🇦🇸': 'sm',
    '🇦🇨': 'en',
    '🇦🇩': 'ca',
    '🇦🇪': 'ar',
    '🇦🇬': 'en',
    '🇦🇮': 'en',
    '🇦🇱': 'sq',
    '🇦🇲': 'hy',
    '🇦🇴': 'pt-PT',
    '🇦🇶': 'en',
    '🇦🇷': 'es',
    '🇦🇹': 'de',
    '🇦🇺': 'en',
    '🇦🇼': 'nl',
    '🇦🇽': 'sv',
    '🇦🇿': 'az',
    '🇧🇸': 'en',
    '🇧🇦': 'bs',
    '🇧🇧': 'en',
    '🇧🇩': 'bn',
    '🇧🇪': 'fr',
    '🇧🇫': 'fr',
    '🇧🇬': 'bg',
    '🇧🇭': 'ar',
    '🇧🇮': 'fr',
    '🇧🇯': 'fr',
    '🇧🇱': 'fr',
    '🇧🇲': 'en',
    '🇧🇳': 'ms',
    '🇧🇴': 'es',
    '🇧🇶': 'nl',
    '🇧🇷': 'pt-PT',
    '🇧🇹': 'ne',
    '🇧🇻': 'is',
    '🇧🇼': 'en',
    '🇧🇾': 'be',
    '🇧🇿': 'en',
    '🇨🇦': 'en',
    '🇨🇨': 'en',
    '🇨🇩': 'fr',
    '🇨🇫': 'fr',
    '🇨🇬': 'fr',
    '🇨🇭': 'de',
    '🇨🇮': 'fr',
    '🇨🇰': 'mi',
    '🇨🇱': 'es',
    '🇨🇲': 'fr',
    '🇨🇳': 'zh-TW',
    '🇨🇴': 'es',
    '🇨🇵': 'fr',
    '🇨🇷': 'es',
    '🇨🇺': 'es',
    '🇨🇻': 'pt-PT',
    '🇨🇼': 'nl',
    '🇨🇽': 'zh-CN',
    '🇨🇾': 'el',
    '🇨🇿': 'cs',
    '🇩🇪': 'de',
    '🇩🇬': 'en',
    '🇩🇯': 'fr',
    '🇩🇰': 'da',
    '🇩🇲': 'en',
    '🇩🇴': 'es',
    '🇩🇿': 'ar',
    '🇪🇦': 'es',
    '🇪🇨': 'es',
    '🇪🇪': 'et',
    '🇪🇬': 'ar',
    '🇪🇭': 'ar',
    '🇪🇷': 'en',
    '🇪🇸': 'es',
    '🇪🇹': 'am',
    '🇪🇺': 'en',
    '🇫🇮': 'fi',
    '🇫🇯': 'hi',
    '🇫🇰': 'en',
    '🇫🇲': 'en',
    '🇫🇴': 'da',
    '🇫🇷': 'fr',
    '🇬🇦': 'fr',
    '🇬🇧': 'en',
    '🇬🇩': 'en',
    '🇬🇪': 'ka',
    '🇬🇫': 'fr',
    '🇬🇬': 'en',
    '🇬🇭': 'en',
    '🇬🇮': 'en',
    '🇬🇱': 'en',
    '🇬🇲': 'en',
    '🇬🇳': 'fr',
    '🇬🇵': 'fr',
    '🇬🇶': 'fr',
    '🇬🇷': 'el',
    '🇬🇸': 'en',
    '🇬🇹': 'es',
    '🇬🇺': 'en',
    '🇬🇼': 'pt-PT',
    '🇬🇾': 'en',
    '🇭🇰': 'zh-CN',
    '🇭🇲': 'en',
    '🇭🇳': 'es',
    '🇭🇷': 'hr',
    '🇭🇹': 'ht',
    '🇭🇺': 'hu',
    '🇮🇨': 'es',
    '🇮🇩': 'id',
    '🇮🇪': 'ga',
    '🇮🇱': 'iw',
    '🇮🇲': 'en',
    '🇮🇳': 'hi',
    '🇮🇴': 'en',
    '🇮🇶': 'ku',
    '🇮🇷': 'fa',
    '🇮🇸': 'is',
    '🇮🇹': 'it',
    '🇯🇪': 'en',
    '🇯🇲': 'en',
    '🇯🇴': 'ar',
    '🇯🇵': 'ja',
    '🇰🇪': 'sw',
    '🇰🇬': 'ky',
    '🇰🇭': 'km',
    '🇰🇮': 'en',
    '🇰🇲': 'fr',
    '🇰🇳': 'en',
    '🇰🇵': 'ko',
    '🇰🇷': 'ko',
    '🇰🇼': 'ar',
    '🇰🇾': 'en',
    '🇰🇿': 'kk',
    '🇱🇦': 'lo',
    '🇱🇧': 'ar',
    '🇱🇨': 'en',
    '🇱🇮': 'ge',
    '🇱🇰': 'ta',
    '🇱🇷': 'en',
    '🇱🇸': 'en',
    '🇱🇹': 'lt',
    '🇱🇺': 'lb',
    '🇱🇻': 'lv',
    '🇱🇾': 'ar',
    '🇲🇦': 'ar',
    '🇲🇨': 'fr',
    '🇲🇩': 'ro',
    '🇲🇪': 'en',
    '🇲🇫': 'fr',
    '🇲🇬': 'mg',
    '🇲🇭': 'en',
    '🇲🇰': 'mk',
    '🇲🇱': 'fr',
    '🇲🇲': 'my',
    '🇲🇳': 'mn',
    '🇲🇴': 'zh-CN',
    '🇲🇵': 'en',
    '🇲🇶': 'fr',
    '🇲🇷': 'ar',
    '🇲🇸': 'en',
    '🇲🇹': 'mt',
    '🇲🇺': 'en',
    '🇲🇻': 'en',
    '🇲🇼': 'en',
    '🇲🇽': 'es',
    '🇲🇾': 'ms',
    '🇲🇿': 'pt-PT',
    '🇳🇦': 'en',
    '🇳🇨': 'fr',
    '🇳🇪': 'fr',
    '🇳🇫': 'en',
    '🇳🇬': 'en',
    '🇳🇮': 'es',
    '🇳🇱': 'nl',
    '🇳🇴': 'no',
    '🇳🇵': 'ne',
    '🇳🇷': 'en',
    '🇳🇺': 'en',
    '🇳🇿': 'mi',
    '🇴🇲': 'ar',
    '🇵🇦': 'es',
    '🇵🇪': 'es',
    '🇵🇫': 'fr',
    '🇵🇬': 'en',
    '🇵🇭': 'tl',
    '🇵🇰': 'en',
    '🇵🇱': 'pl',
    '🇵🇲': 'fr',
    '🇵🇳': 'en',
    '🇵🇷': 'es',
    '🇵🇸': 'ar',
    '🇵🇹': 'pt-PT',
    '🇵🇼': 'en',
    '🇵🇾': 'es',
    '🇶🇦': 'ar',
    '🇷🇪': 'fr',
    '🇷🇴': 'ro',
    '🇷🇸': 'sr',
    '🇷🇺': 'ru',
    '🇷🇼': 'en',
    '🇸🇦': 'ar',
    '🇸🇧': 'en',
    '🇸🇨': 'fr',
    '🇸🇩': 'ar',
    '🇸🇪': 'sv',
    '🇸🇬': 'zh-TW',
    '🇸🇭': 'en',
    '🇸🇮': 'sl',
    '🇸🇯': 'nl',
    '🇸🇰': 'sk',
    '🇸🇱': 'en',
    '🇸🇲': 'it',
    '🇸🇳': 'fr',
    '🇸🇴': 'so',
    '🇸🇷': 'nl',
    '🇸🇸': 'en',
    '🇸🇹': 'pt-PT',
    '🇸🇻': 'es',
    '🇸🇽': 'nl',
    '🇸🇾': 'ar',
    '🇸🇿': 'en',
    '🇹🇦': 'en',
    '🇹🇨': 'en',
    '🇹🇩': 'fr',
    '🇹🇫': 'fr',
    '🇹🇬': 'fr',
    '🇹🇭': 'th',
    '🇹🇯': 'tg',
    '🇹🇰': 'en',
    '🇹🇱': 'pt-PT',
    '🇹🇲': 'en',
    '🇹🇳': 'ar',
    '🇹🇴': 'en',
    '🇹🇷': 'tr',
    '🇹🇹': 'en',
    '🇹🇻': 'en',
    '🇹🇼': 'zh-CN',
    '🇹🇿': 'sw',
    '🇺🇦': 'uk',
    '🇺🇬': 'sw',
    '🇺🇲': 'en',
    '🇺🇳': 'en',
    '🇺🇸': 'en',
    '🇺🇾': 'es',
    '🇺🇿': 'uz',
    '🇻🇦': 'it',
    '🇻🇨': 'en',
    '🇻🇪': 'es',
    '🇻🇬': 'en',
    '🇻🇮': 'en',
    '🇻🇳': 'vi',
    '🇻🇺': 'fr',
    '🇼🇫': 'fr',
    '🇼🇸': 'sm',
    '🇽🇰': 'sq',
    '🇾🇪': 'ar',
    '🇾🇹': 'fr',
    '🇿🇦': 'af',
    '🇿🇲': 'en',
    '🇿🇼': 'sn',
    '🏴󠁧󠁢󠁥󠁮󠁧󠁿': 'en',
    '🏴󠁧󠁢󠁷󠁬󠁳󠁿': 'cy',
    '🇦🇫': 'fa-AF',
}

LANGKEYS = list(LANGUAGES.keys())
LANGNAMES = list(LANGUAGES.values())

LANGCODES = dict(map(reversed, LANGUAGES.items()))
DEFAULT_RAISE_EXCEPTION = False
DUMMY_DATA = [[["", None, None, 0]], None, "en", None,
              None, None, 1, None, [["en"], None, [1], ["en"]]]
